In [7]:
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
c_df=pd.read_csv('unesco_cleaned.csv')

In [10]:

c_df.head()

,Category,Country,Region,Site_Name,Year,Danger,Longitude,Latitude,Area,Age,Area_Category,Danger_Status,Decade
0,Natural,United States of America,Europe and North America,Yellowstone National Park,1978,0,-110.827780,44.460560,898349.0,48,Large,Safe,1970
1,Cultural,United States of America,Europe and North America,Mesa Verde National Park,1978,0,-108.485556,37.261667,21043.0,48,Medium,Safe,1970
2,Cultural,Canada,Europe and North America,L’Anse aux Meadows National Historic Site,1978,0,-55.616667,51.466667,7991.0,48,Small,Safe,1970
3,Natural,Canada,Europe and North America,Nahanni National Park,1978,0,-125.589444,61.547222,476560.0,48,Large,Safe,1970
4,Cultural,Germany,Europe and North America,Aachen Cathedral,1978,0,6.084444,50.774444,0.2,48,Small,Safe,1970

In [11]:
c_df.shape

(1121, 13)

In [13]:
c_df.columns

Index(['Category', 'Country', 'Region', 'Site_Name', 'Year', 'Danger',
       'Longitude', 'Latitude', 'Area', 'Age', 'Area_Category',
       'Danger_Status', 'Decade'],
      dtype='str')

In [14]:
c_df.describe()

,Year,Danger,Longitude,Latitude,Area,Age,Decade
count,1121.000000,1121.000000,1121.000000,1121.000000,1.121000e+03,1121.000000,1121.000000
mean,1997.819804,0.047279,20.387607,28.948467,3.306856e+05,28.180196,1993.104371
std,11.655302,0.212330,63.082727,23.692877,2.894290e+06,11.655302,11.832038
min,1978.000000,0.000000,-179.715278,-54.594722,0.000000e+00,7.000000,1970.000000
25%,1987.000000,0.000000,-3.328986,17.483330,8.920000e+00,19.000000,1980.000000
50%,1998.000000,0.000000,16.383333,36.100833,1.765000e+02,28.000000,1990.000000
75%,2007.000000,0.000000,50.512778,45.767220,1.229000e+04,39.000000,2000.000000
max,2019.000000,1.000000,178.834533,71.188889,6.729690e+07,48.000000,2010.000000

In [15]:
c_df['Category'].value_counts() # Count sites by category

Category
Cultural    869
Natural     213
Mixed        39
Name: count, dtype: int64

In [16]:
c_df['Country'].value_counts().head(10) # Count sites by country

Country
China                                                   54
Italy                                                   49
Spain                                                   44
France                                                  41
Germany                                                 39
India                                                   37
Mexico                                                  35
United Kingdom of Great Britain and Northern Ireland    31
Russian Federation                                      25
Iran (Islamic Republic of)                              24
Name: count, dtype: int64

In [17]:
c_df['Region'].value_counts() # Count sites by region

Region
Europe and North America                                                         528
Asia and the Pacific                                                             266
Latin America and the Caribbean                                                  142
Africa                                                                            96
Arab States                                                                       86
Europe and North America,Asia and the Pacific                                      2
Europe and North America,Asia and the Pacific,Latin America and the Caribbean      1
Name: count, dtype: int64

In [18]:
danger_sites = c_df[c_df['Danger'] == 1] # Find danger sites

danger_sites.head()

,Category,Country,Region,Site_Name,Year,Danger,Longitude,Latitude,Area,Age,Area_Category,Danger_Status,Decade
17,Cultural,Syrian Arab Republic,Arab States,Ancient City of Damascus,1979,1,36.306390,33.511390,86.12,47,Small,In Danger,1970
27,Natural,United States of America,Europe and North America,Everglades National Park,1979,1,-80.996389,25.554444,567017.00,47,Large,In Danger,1970
45,Natural,Democratic Republic of the Congo,Africa,Virunga National Park,1979,1,29.166667,0.916667,800000.00,47,Large,In Danger,1970
55,Cultural,Egypt,Arab States,Abu Mena,1979,1,29.666667,30.835833,182.72,47,Small,In Danger,1970
70,Cultural,Syrian Arab Republic,Arab States,Site of Palmyra,1980,1,38.266670,34.554170,1640.00,46,Small,In Danger,1980

In [19]:
c_df.sort_values(by='Year').head(10)  # Oldest sites

,Category,Country,Region,Site_Name,Year,Danger,Longitude,Latitude,Area,Age,Area_Category,Danger_Status,Decade
0,Natural,United States of America,Europe and North America,Yellowstone National Park,1978,0,-110.827780,44.460560,898349.0,48,Large,Safe,1970
1,Cultural,United States of America,Europe and North America,Mesa Verde National Park,1978,0,-108.485556,37.261667,21043.0,48,Medium,Safe,1970
2,Cultural,Canada,Europe and North America,L’Anse aux Meadows National Historic Site,1978,0,-55.616667,51.466667,7991.0,48,Small,Safe,1970
3,Natural,Canada,Europe and North America,Nahanni National Park,1978,0,-125.589444,61.547222,476560.0,48,Large,Safe,1970
4,Cultural,Germany,Europe and North America,Aachen Cathedral,1978,0,6.084444,50.774444,0.2,48,Small,Safe,1970
5,Cultural,Ethiopia,Africa,"Rock-Hewn Churches, Lalibela",1978,0,39.040420,12.029350,0.0,48,Small,Safe,1970
6,Natural,Ethiopia,Africa,Simien National Park,1978,0,38.066667,13.183333,13600.0,48,Medium,Safe,1970
7,Cultural,Senegal,Africa,Island of Gorée,1978,0,-17.400830,14.667220,0.0,48,Small,Safe,1970
8,Natural,Ecuador,Latin America and the Caribbean,Galápagos Islands,1978,0,-91.000000,-0.816670,14066514.0,48,Large,Safe,1970
9,Cultural,Ecuador,Latin America and the Caribbean,City of Quito,1978,0,-78.500000,-0.003889,320.0,48,Small,Safe,1970

In [20]:
c_df.sort_values(by='Year', ascending=False).head(10) # Newest sites

,Category,Country,Region,Site_Name,Year,Danger,Longitude,Latitude,Area,Age,Area_Category,Danger_Status,Decade
1105,Cultural,India,Asia and the Pacific,"Jaipur City, Rajasthan",2019,0,75.787222,26.907861,710.00,7,Small,Safe,2010
1120,Cultural,Australia,Asia and the Pacific,Budj Bim Cultural Landscape,2019,0,141.885278,-38.081111,9935.00,7,Small,Safe,2010
1104,Cultural,China,Asia and the Pacific,Archaeological Ruins of Liangzhu City,2019,0,119.990833,30.395556,1433.66,7,Small,Safe,2010
1103,Cultural,Iraq,Arab States,Babylon,2019,0,44.420833,32.541969,1054.30,7,Small,Safe,2010
1102,Natural,Iran (Islamic Republic of),Asia and the Pacific,Hyrcanian Forests,2019,0,55.724278,37.421472,129484.74,7,Large,Safe,2010
1101,Cultural,Indonesia,Asia and the Pacific,Ombilin Coal Mining Heritage of Sawahlunto,2019,0,100.737883,-0.766626,268.18,7,Small,Safe,2010
1100,Cultural,Italy,Europe and North America,Le Colline del Prosecco di Conegliano e Valdob...,2019,0,12.226111,45.953028,20334.20,7,Medium,Safe,2010
1099,Natural,China,Asia and the Pacific,Migratory Bird Sanctuaries along the Coast of ...,2019,0,121.016814,32.931944,188643.00,7,Large,Safe,2010
1098,Mixed,Brazil,Latin America and the Caribbean,Paraty and Ilha Grande – Culture and Biodiversity,2019,0,-44.685369,-23.018606,204634.00,7,Large,Safe,2010
1097,Cultural,Japan,Asia and the Pacific,Mozu-Furuichi Kofun Group: Mounded Tombs of An...,2019,0,135.609444,34.562222,166.66,7,Small,Safe,2010

In [21]:
c_df['Area'].mean() # Average area

np.float64(330685.55237546837)

In [22]:
c_df['Decade'].value_counts().sort_index() # Sites by decade

Decade
1970     57
1980    262
1990    309
2000    262
2010    231
Name: count, dtype: int64